- name: Create an incident in ServiceNow
  hosts: "{{ vm_name }}"
  gather_facts: yes
  connection: local
  
  tasks: 
  
  - name: Create an incident in ServiceNow
    servicenow.itsm.incident:
      state: new
      description: "{{ sn_description | default(omit) }}"
      short_description: "{{ incident_description }}"
      caller: "{{ caller_name }}"
      urgency: "{{ sn_urgency }}"
      impact: "{{ sn_impact }}"
      other:
        u_operating_system: "{{ os | default(omit) }}"
        u_ip_address: "{{ ip_addr | default(omit) }}"
        u_vm_name: "{{ inventory_hostname | default(omit) }}"       
    register: new_incident
    delegate_to: localhost

  - debug: 
      var: new_incident.record.number
